# Generated by Django 3.0.7 on 2020-08-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('paragraph_1', models.TextField(blank=True)),
                ('paragraph_2', models.TextField(blank=True)),
                ('paragraph_3', models.TextField(blank=True)),
                ('paragraph_4', models.TextField(blank=True)),
                ('paragraph_5', models.TextField(blank=True)),
                ('paragraph_6', models.TextField(blank=True)),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('paragraph_7', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('paragraph_1', models.TextField(blank=True)),
                ('paragraph_2', models.TextField(blank=True)),
                ('paragraph_3', models.TextField(blank=True)),
                ('paragraph_4', models.TextField(blank=True)),
                ('paragraph_5', models.TextField(blank=True)),
                ('paragraph_6', models.TextField(blank=True)),
                ('paragraph_7', models.TextField(blank=True)),
                ('paragraph_8', models.TextField(blank=True)),
                ('paragraph_9', models.TextField(blank=True)),
                ('paragraph_10', models.TextField(blank=True)),
                ('paragraph_11', models.TextField(blank=True)),
                ('paragraph_12', models.TextField(blank=True)),
                ('paragraph_13', models.TextField(blank=True)),
                ('paragraph_14', models.TextField(blank=True)),
                ('paragraph_15', models.TextField(blank=True)),
                ('paragraph_16', models.TextField(blank=True)),
                ('paragraph_17', models.TextField(blank=True)),
                ('paragraph_18', models.TextField(blank=True)),
                ('paragraph_19', models.TextField(blank=True)),
                ('paragraph_20', models.TextField(blank=True)),
                ('paragraph_21', models.TextField(blank=True)),
                ('paragraph_22', models.TextField(blank=True)),
                ('paragraph_23', models.TextField(blank=True)),
                ('paragraph_24', models.TextField(blank=True)),
                ('paragraph_25', models.TextField(blank=True)),
                ('paragraph_26', models.TextField(blank=True)),
                ('paragraph_27', models.TextField(blank=True)),
                ('paragraph_28', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('paragraph_1', models.TextField(blank=True)),
                ('paragraph_2', models.TextField(blank=True)),
                ('paragraph_3', models.TextField(blank=True)),
                ('paragraph_4', models.TextField(blank=True)),
                ('paragraph_5', models.TextField(blank=True)),
                ('paragraph_6', models.TextField(blank=True)),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('paragraph_7', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SustainableDrainage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('paragraph_1', models.TextField(blank=True)),
            ],
        ),
    ]
