# Generated by Django 3.0.7 on 2020-08-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wsdSA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('paragraph_1', models.TextField(blank=True)),
                ('paragraph_2', models.TextField(blank=True)),
                ('paragraph_3', models.TextField(blank=True)),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Modelling',
            new_name='Modellings',
        ),
        migrations.AddField(
            model_name='cities',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
