# Generated by Django 3.0.7 on 2020-08-18 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200802_2044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='About',
        ),
    ]
