# Generated by Django 3.0.7 on 2020-08-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('paragraph_1', models.TextField(blank=True)),
                ('paragraph_2', models.TextField(blank=True)),
                ('paragraph_3', models.TextField(blank=True)),
                ('paragraph_4', models.TextField(blank=True)),
                ('paragraph_5', models.TextField(blank=True)),
                ('paragraph_6', models.TextField(blank=True)),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('paragraph_7', models.TextField(blank=True)),
            ],
        ),
    ]
