# Generated by Django 3.0.7 on 2020-08-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepages',
            name='paragraph_3',
        ),
        migrations.RemoveField(
            model_name='homepages',
            name='paragraph_4',
        ),
        migrations.RemoveField(
            model_name='homepages',
            name='paragraph_5',
        ),
        migrations.RemoveField(
            model_name='homepages',
            name='paragraph_6',
        ),
        migrations.RemoveField(
            model_name='homepages',
            name='paragraph_7',
        ),
        migrations.AddField(
            model_name='homepages',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='homepages',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='homepages',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='homepages',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='homepages',
            name='sub_title',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
