# Generated by Django 3.0.7 on 2020-08-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='capeTown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('paragraph_1', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='casesoverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('paragraph_1', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='centurycitys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('paragraph_1', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='cotswolds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('paragraph_1', models.TextField(blank=True)),
                ('paragraph_2', models.TextField(blank=True)),
                ('paragraph_3', models.TextField(blank=True)),
                ('paragraph_4', models.TextField(blank=True)),
                ('paragraph_5', models.TextField(blank=True)),
                ('paragraph_6', models.TextField(blank=True)),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('paragraph_7', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='hawaans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('paragraph_1', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='kzns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('paragraph_1', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='menlynn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('paragraph_1', models.TextField(blank=True)),
                ('paragraph_2', models.TextField(blank=True)),
                ('paragraph_3', models.TextField(blank=True)),
                ('paragraph_4', models.TextField(blank=True)),
                ('paragraph_5', models.TextField(blank=True)),
                ('paragraph_6', models.TextField(blank=True)),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('paragraph_7', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='pietermaritzburgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('paragraph_1', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='rainbows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('paragraph_1', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('paragraph_1', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoofGarde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('paragraph_1', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='verde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('paragraph_1', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('paragraph_1', models.TextField(blank=True)),
            ],
        ),
    ]
