# Generated by Django 3.0.7 on 2020-08-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Casestudies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotswolds',
            name='paragraph_4',
        ),
        migrations.RemoveField(
            model_name='cotswolds',
            name='paragraph_5',
        ),
        migrations.RemoveField(
            model_name='cotswolds',
            name='paragraph_6',
        ),
        migrations.RemoveField(
            model_name='cotswolds',
            name='paragraph_7',
        ),
    ]
