# Generated by Django 3.0.7 on 2020-08-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casestudies', '0002_auto_20200819_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menlynn',
            name='paragraph_4',
        ),
        migrations.RemoveField(
            model_name='menlynn',
            name='paragraph_5',
        ),
        migrations.RemoveField(
            model_name='menlynn',
            name='paragraph_6',
        ),
        migrations.RemoveField(
            model_name='menlynn',
            name='paragraph_7',
        ),
        migrations.AddField(
            model_name='capetown',
            name='paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='capetown',
            name='paragraph_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='capetown',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='casesoverview',
            name='paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casesoverview',
            name='paragraph_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casesoverview',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='centurycitys',
            name='paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='centurycitys',
            name='paragraph_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='centurycitys',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='hawaans',
            name='paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hawaans',
            name='paragraph_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hawaans',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='kzns',
            name='paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kzns',
            name='paragraph_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kzns',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='pietermaritzburgs',
            name='paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pietermaritzburgs',
            name='paragraph_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pietermaritzburgs',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='rainbows',
            name='paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rainbows',
            name='paragraph_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rainbows',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='report',
            name='paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='paragraph_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='roofgarde',
            name='paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roofgarde',
            name='paragraph_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roofgarde',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='verde',
            name='paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='verde',
            name='paragraph_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='verde',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='wits',
            name='paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wits',
            name='paragraph_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wits',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
